### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ajuckler** [ofirbo/Scatter#1]
Hello,

I'd like to use your code for one project. Could you tell me what license it is?

Legally speaking, without a license nobody can actually use your code.
Here's some GitHub explanation on licensing if this may help.
[GitHub - Licensing a repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)

**Comment by ofirbo** [comment]
Hi, I'm not a programmer so I hope that by adding the LICENSE.md file you can use it.

**Comment by ajuckler** [comment]
Yes that's perfect. Thank you so much
